- name: Create logind conf directory
  file:
    path: /etc/systemd/logind.conf.d
    state: directory
    mode: 0755

- name: Configure logind
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/logind.conf.d
    mode: preserve
  loop:
    - idle-action.conf
