- name: Enable copr repos
  command: dnf copr -y enable {{ item }}
  args:
    warn: false
  loop:
    - rockowitz/ddcutil

- name: Install packages
  dnf:
    name:
      - ddcutil

- name: Copy i2c udev rule
  copy:
    src: /usr/share/ddcutil/data/45-ddcutil-i2c.rules
    dest: /etc/udev/rules.d
    mode: preserve
  become: yes

- name: Create i2c group
  group:
    name: i2c
    system: yes
  become: yes

- name: Add user to i2c group
  user:
    name: '{{ user }}'
    groups: i2c
    append: yes
  become: yes
