- name: Set up pam_environment for gpg-agent-ssh
  copy:
    src: pam_environment
    dest: "{{ homedir }}/.pam_environment"

- name: Enable gpg systemd user units
  systemd:
    name: "{{ item }}"
    enabled: yes
    scope: user
  loop:
    - gpg-agent-ssh.socket
