- name: Set zsh as user shell
  user:
    name: '{{ ansible_user_id }}'
    shell: /usr/bin/zsh

- name: Add user to mock group
  user:
    name: '{{ ansible_user_id }}'
    groups: mock
    append: yes

# Required to access serial ports.
- name: Add user to dialout group
  user:
    name: '{{ ansible_user_id }}'
    groups: dialout
    append: yes
