- name: Remove packages included in basic-desktop software selection
  dnf:
    name:
      - awesome
      - cronie
      - fprintd
      - i3
      - initial-setup-gui
      - openbox
      - pcsc-lite
      - qtile
      - ratpoison
      - virtualbox-guest-additions
      - xmonad-core
    state: absent

- name: Autoremove leaf packages
  dnf: autoremove=yes
